steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pos:v1.1', '.']

   # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pos:v1.1']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'cloudrun-srv', '--image', 'gcr.io/$PROJECT_ID/pos:v1.1', '--region', 'us-central1']
  # Push to GCR container registery
images:
    - gcr.io/$PROJECT_ID/pos:v1.1
options:
  logging: CLOUD_LOGGING_ONLY