steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/pos:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/pos:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=./deployment.yaml
    - --image=gcr.io/${PROJECT_ID}/pos:$COMMIT_SHA
    - --location=us-central1
    - --cluster=my-gke-cluster
options:
  logging: CLOUD_LOGGING_ONLY
